
jQuery(document).ready(function() {
  jQuery('input[name^="profile_main[field_address][und][0][city]"], input[name^="field_departure_from[und][0][city]"], input[name^="field_destination[und][0][city]"]').combobox([
    'Aleppo',
    'Damascus',
    'Daraa',
    'Deir ez-Zor',
    'Hama',
    'Al-Hasakah',
    'Homs',
    'Idlib',
    'Latakia',
    'Quneitra',
    'Ar-Raqqah',
    'As-Suwayda',
    'Tartus',
    'Afrin',
    'Arihah',
    'Atarib',
    'Ayn al-Arab',
    "A'zaz",
    'Al-Bab',
    'Baniyas',
    'Abu Kamal',
    'Darayya',
    'Dayr Hafir',
    'Douma',
    'Duraykish',
    'Fiq',
    'Al-Haffah',
    'Harem',
    "Izra'",
    'Jableh',
    'Jarabulus',
    'Jisr ash-Shugur',
    'Maarat al-Numaan',
    'Al-Malikiyah',
    'Manbij',
    'Masyaf',
    'Mayadin',
    'Mhardeh',
    'Al-Mukharram',
    'An-Nabk',
    'Palmyra',
    'Qamishli',
    'Qardaha',
    'Qatana',
    'Qudsaya',
    'Al-Qusayr',
    'Al-Qutayfah',
    "Ra's al-'Ayn",
    'Al-Rastan',
    'As-Safira',
    'Safita',
    'Salamiyah',
    'Salkhad',
    'Al-Sanamayn',
    'Shahba',
    'Ash-Shaykh Badr',
    'Al-Suqaylabiyah',
    'Tal Abyad',
    'Talkalakh',
    'Al-Tall',
    'Al-Thawrah',
    'Yabrud',
    'Zabadani',
    'Sayyidah Zaynab',
    'Al-Darbasiyah',
    'Al-Hajar al-Aswad',
    'Binnish',
    'Bosra',
    "Dayr 'Atiyah",
    'Harasta',
    'Jaramana',
    'Kafr Nabl',
    'Khan Shaykhun',
    "Ma'arrat Misrin",
    'Nawa',
    'Salqin',
    'Saraqib',
    'Talbiseh'
  ]);
});